### ISSUE TITLE
Cant save record

### ISSUE THREAD

**Issue by stefan694** [openscript/awesome_hstore_translate#3]
Hi I have this issue after following the doc:
`PG::InternalError: ERROR: Unexpected end of string : SELECT 1 AS one FROM "tags" WHERE "tags"."title" = $1 LIMIT $2`

**Comment by openscript** [comment]
Hi @stefan694 

Thank you for adding an issue. Is it possible to provide more information? What exactly did you do? Which code caused that error? Can you add the whole stacktrace?

After I have enough information to reproduce the bug, I'll fix it :-)

**Comment by openscript** [comment]
Did you activate the `hstore` extension?

```
class CreatePages < ActiveRecord::Migration
  def change
    create_table :pages do |t|
      enable_extension 'hstore' unless extension_enabled?('hstore')
      t.column :title, :hstore
      t.column :content, :hstore
      t.timestamps
    end
  end
end
```

**Comment by stefan694** [comment]
added hstore extension: 
`psql -d abcdent_tv_development -c 'create extension hstore;'`

added gem : 
`gem 'awesome_hstore_translate'`

added migration :
`class AddTranslationsToTags < ActiveRecord::Migration[5.0]
  def change
    add_column    :tags,          :title,     :hstore
  end
end`

added translates on model : 
`class Tag < ApplicationRecord
    translates :title
  end
`

rails console : 

t = Tag.new
`#<Tag:0x00000008cff3e8> {
            :id => nil,
            :created_at => nil,
            :updated_at => nil,
            :title => nil
}
`
t.title = "fr"
`"fr"`

t.save

`(0.4ms)  BEGIN
  Tag Exists (1.4ms)  SELECT  1 AS one FROM "tags" WHERE "tags"."title" = $1 LIMIT $2  [["title", "fr"], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  Unexpected end of string
: SELECT  1 AS one FROM "tags" WHERE "tags"."title" = $1 LIMIT $2
`

**Comment by openscript** [comment]
Don't forget to star the project if you like it. This would help to make it more popular :-)
