### ISSUE TITLE
`find_by` won't pass the correct args to `super`

### ISSUE THREAD

**Issue by sebweaver** [openscript/awesome_hstore_translate#5]
In `active_record/core.rb`:

```ruby
        def find_by(*args)
          attrs = args.first
          if attrs.is_a?(Hash) && contains_translated_attributes(attrs)
            where(attrs).limit(1).first
          else
            super(args)
          end
        end
```
The line:

`super(args)`

Should use the splat operator:

`super(*args)`

Or even simpler:

`super`

Otherwise args are squashed into a single array.

**Comment by openscript** [comment]
You are right. Thank you for contributing. I've fixed this.
